### ISSUE TITLE
For macos M1 chip, I hope to upgrade the project chip to Node js 16.x version

### ISSUE THREAD

**Issue by mqllin** [RSamaium/RPG-JS#177]
I'm a Java Scrpit developer, and I liked the framework from the first moment I saw it. I run everything fine in Windows. But when I switched to the Mac OS M1 Chip, I couldn't successfully launch the program. Because in Node JS 14.x , Node Canvas and Jest (maybe) do not support M1 Chip. I was unable to npm install successfully.Hopefully, the project will be upgraded to at least version 16!

**Comment by RSamaium** [comment]
Hello,

It is planned to make it compatible with NodeJS 16+ versions but not in the short term (from 2023)

**Comment by cleentfaar** [comment]
@RSamaium hi! I just stumbled upon this awesome framework for a project I'm working on. Thing is, like @mqllin I work on a MacBook (m2) and am facing the same problem. 

Waiting for next year is a bit difficult for me but perhaps I can take some of the work out of your hands?

Can you point me to the place in your codebase where to start fixing this dependency issue (assuming simply raising version constraints won't fix it)?

**Comment by RSamaium** [comment]
@cleentfaar Hello,

The goal is to update the compiler:

https://github.com/RSamaium/RPG-JS/tree/v3/packages/compiler, and mainly `node-sass` module, it should be put on version 6+ for compatibility with NodeJS 16 (https://www.npmjs.com/package/node-sass)

I already tried but it causes other difficulties, because it is necessary to update webpack, and to change the configuration in the webpack-* files

I thought that the easiest way was to redo the compiler with Vite in order to optimize the compiler and to switch to the latest version of NodeJS. But in a first time, we can fix the problem with Webpack :)

If you feel comfortable to do it, don't hesitate to propose a pull request !

**Comment by pabSec** [comment]
You could use a linux container in docker until there's a solution:

```
version: "3.4"
services:
  server:
    image: node:14.21.1-bullseye
    volumes:
      - ../my-rpg-game:/development
    working_dir: /development
    platform: linux/amd64
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm run dev"
```
